### ISSUE TITLE
datum v poli 588

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/WA-KAT#100]
WA-KAT automaticky generuje v poli 588 datum ve tvaru např. 02.03.17. Pokud je číslovka v datu jednomístná, neměla by před ní být 0 (viz příklady dole). Šlo by to řešit?

 
nyní:
pole 588 Název z titulní obrazovky (náhled z 03.02.2017)

ideálně:
pole 588 Název z titulní obrazovky (náhled z 3.2.2017)

**Comment by Bystroushaak** [comment]
Implementováno ve verzi 1.1.9. Prosím @westfood o nasazení nové verze.

**Comment by kvasnicaj** [comment]
teď se o to stará @JanMeritus  :)

**Comment by Bystroushaak** [comment]
Ah, ok. Prosím tedy @JanMeritus ideálně o nový build úplně celé docker image, pokud to tak stále provozujete.

**Comment by JanMeritus** [comment]
jj, stale. Cajk, zitra sa na to podivam.

**Comment by mariehaskovcova** [comment]
otestuju začátkem měsíce, až bude v datu aspoň jedna jenomístná číslice :)

**Comment by mariehaskovcova** [comment]
otestováno a funguje, díky
