### ISSUE TITLE
Connect with seeder

### ISSUE THREAD

**Issue by Bystroushaak** [WebArchivCZ/WA-KAT#51]
Related: WebArchivCZ/Seeder#162

**Comment by Bystroushaak** [comment]
Todo: WebArchivCZ/Seeder#194

**Comment by Bystroushaak** [comment]
Potřeba API, kam budu odesílat data.

Související ISSUE: WebArchivCZ/Seeder#193

**Comment by Visgean** [comment]
Uz by mel bezet na http://war.webarchiv.cz/

**Comment by Bystroushaak** [comment]
http://seeder.readthedocs.io/en/latest/api.html

**Comment by westfood** [comment]
Hele 8080 se mi bude na ostrým serveru hádat s Tomcatem: https://github.com/WebArchivCZ/WA-KAT/issues/81 - šlo by to nějak jednoduše?

**Comment by Bystroushaak** [comment]
@westfood: Můžeš mi prosím na m@rfox.eu poslat nějaký login na ten server, abych mohl otestovat ten propoj?

**Comment by westfood** [comment]
Máš VPN? na 22 to zvenku povolený nebude. Ale pushnu na git machines součanej vagrant + ansible a dám ti vědět.

r.

**Comment by westfood** [comment]
Hele a Seederovský seeder_key = WA-KATovský seeder_token ??`

tj. https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/settings/local_settings.template.py 
versus http://wa-kat.readthedocs.io/en/latest/admin_manual.html //  "SEEDER_TOKEN": "1acedb1b6347d9d40fe2f055aa6d3c077f106894"

**Comment by Bystroushaak** [comment]
Asi jo. Ten token to generovalo samo, tak bych do toho asi ani nehrabal, jen se musí ve WA KATu správně nastavit podle http://seeder.readthedocs.io/en/latest/api.html

**Comment by Bystroushaak** [comment]
To co je uvedený v dokumentaci je jen example, určitě ho tam nenastavuj.

**Comment by Bystroushaak** [comment]
VPN nemám. Potřebuju přístup do Seederu, ne na ten linuxový stroj.

**Comment by westfood** [comment]
hmm... testnu..

testovací seeder:
http://war.webarchiv.cz/ / Visgean:Visgean

ale koukám, že wa-kat tam nějak blbne a není přístupný z 8081.. ani nejde sejmout ctrl+c .. kouknu ještě na to.. on je tam primárně problém, že 8081 je zablokovanej na FW národky, takže wa-kat stejně neuvidíš.. ozvu se přes víkend..

sudo docker run -p 8081:8080 nlcr/wa-kat
[sudo] password for rudolf:
Restarting supervisor: supervisord.
Bottle v0.12.9 server starting up (using PasteServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

**Comment by Bystroushaak** [comment]
Aha. To chtělo velké V.

**Comment by Bystroushaak** [comment]
Já asi teď nepotřebuju přístup na WA KAT u tebe, odladím to na tom demu a pak pushnu update do gitu.

**Comment by Bystroushaak** [comment]
Tak, hotovo. Má to ale několik specifik. Do JSON settings souboru to chce přidat alternativní URL a token. Token ti pošlu na IRC:

```JSON
{
    "SEEDER_TOKEN": "poslu na IRC",
    "SEEDER_INFO_URL": "http://war.webarchiv.cz/api/source/%s/"
}```

**Comment by Bystroushaak** [comment]
Koukám, že už na IRC nejsi. Tak jinam.

**Comment by Bystroushaak** [comment]
Máš to v mailu.
