### ISSUE TITLE
V záznamu chybí další předmětová hesla

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#53]
Do MARCovského záznamu se propíše jen první předmětové heslo, další už ne (pole 650).

**Comment by Bystroushaak** [comment]
Díky, mrknu na to.

**Comment by Bystroushaak** [comment]
Tak, mělo by být opraveno, prosím o otestování. Zároveň jsem odstranil předvyplněné hodnoty v poli URL a ISSN.

**Comment by bjackova** [comment]
Už to funguje :)
