### ISSUE TITLE
Chyba v generování čísla MDT

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#54]
Negeneruje čísla MDT podle předmětových hesel, momentálně se tam jen překopíruje číslo subkonspektu.

**Comment by Bystroushaak** [comment]
Jo, to jsem vzal z ukázkových XML souborů více/méně odhadem.

**Comment by Bystroushaak** [comment]
Jakým způsobem se to má generovat?

**Comment by bjackova** [comment]
ze souboru předmětových autorit - u předmětového hesla uvedená i jeho anglická verze i číselný kód MDT
![predm-heslo-mdt](https://cloud.githubusercontent.com/assets/12845130/12884950/003c3b2a-ce62-11e5-8e8b-8578723a340f.png)

**Comment by Bystroushaak** [comment]
Aj karamba.

**Comment by Bystroushaak** [comment]
Tak, mělo by být opraveno.

**Comment by bjackova** [comment]
Čísla se generují, ale jen pro první 2 předmětová hesla.

**Comment by Bystroushaak** [comment]
Hm. Tam bude někde zrada, podívám se na to.

**Comment by Bystroushaak** [comment]
Tohle nemůžu potvrdit. Bavíme se o poli 080?

**Comment by Bystroushaak** [comment]
Můžeš případně prosím poslat screenshot, kde zakroužkuješ co je špatně, případně nějaké další informace (na jakých klíčových slovech to zkoušíš, isbn atp..)?

**Comment by Bystroushaak** [comment]
Hm. Tohle by mohlo být opraveno opravami zpracování klíčových slov.

@bjackova Můžeš to prosím vyzkoušet?

**Comment by bjackova** [comment]
Otestováno, v pořádku - už to generuje všechna klíč. slova.
