### ISSUE TITLE
Předmětová hesla

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#57]
Některá předmětová hesla nejde zobrazit. Je to u hesel, která mají více výskytů než je počet v rolovacím okně nabídky - např. hudba, literatura - při hledání slova "hudba" se zobrazí abecedně uspořádaný seznam např. adventní hudba, americká hudba .... dechová hudba (další výskyty), ale nedostanu se k dalším heslům v abecedě.

**Comment by Bystroushaak** [comment]
Mrknu na to.

**Comment by Bystroushaak** [comment]
Zvětšil jsem limity na 500 položek a přidal scrollbar na pravou stranu.

**Comment by Bystroushaak** [comment]
Prosím o otestování.
