### ISSUE TITLE
Autor a vydavatel

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#58]
Jsou prohozena pole Autor a Vydavatel - pole Autor se zapisuje do MARC pole 264, které je pro nakladatelské a vydavatelské údaje. U pole Vydavatel nevidím, kam se zapisuje údaj, v záznamu MARC chybí.

**Comment by Bystroushaak** [comment]
Vydavatel se zatím nikam nezapisuje, mám to rozpracované, teď je to v podstatě jen políčko z hlediska designu. Je to ale na vrcholu TODO stacku, tak to bude brzo implementováno.

**Comment by Bystroushaak** [comment]
Hm. Tohle jsem tam zřídil, protože si vzpomínám, jak jsme se o tom bavili, že někdy je autor stránek jiný, než vydavatel.

Myslel jsem to tak, že v případě, že je autor stejný jako vydavatel, tak se vyplňuje autor, který se pak propíše do 264b. Pokud je ale rozdílný, tak se do 264b zapíše vydavatel, a nějak teď nevím, kam se měl zapsat autor.

Nebo jsou ty pravidla jinak?

**Comment by Bystroushaak** [comment]
Přidal jsem tam rozklik, že se vydavatel nezobrazuje vždy.

**Comment by bjackova** [comment]
Je to trochu složitější autor se zapisuje do pole 100 (fyzická os.) nebo 110 (korporace - u nás častější případ) a musí mít autoritní tvar, tzn. ověřuje se přes rejstřík autorit, zatímco vydavatel je v poli 264 b a zapisuje se ve tvaru, jaký je na webu.

**Comment by Bystroushaak** [comment]
Aha, díky za informace.

**Comment by Bystroushaak** [comment]
Ještě mě napadá - jak se řeší situace, kdy autor ještě v autoritách není?

**Comment by bjackova** [comment]
Musíme vytvořit novou autoritu :-)

**Comment by Bystroushaak** [comment]
Takže nikdy nedojde k tomu, aby se vkládal autor, pro kterého zatím není autorita?

Můžu ještě poprosit o ID nějakých záznamů, kde je autor / korporace? Jen abych si byl fakt jistý, kód už částečně připravený mám a přes víkend bych to měl nasadit.

**Comment by bjackova** [comment]
Je to tak, nejdřív se musí autorita vytvořit, alespoň ve formě návrhu (ten tvoříme my, autority to pak ověří a schválí). Např. tady je autorem korporace muzeum 002755224, asociace 002776754, občanské sdružení 002779145. 
Ještě je tam vlastně jeden chyták, autor může být hlavní (pole 100/110) a nebo vedlejší (700/710), tzn. v případě že jsou dva a víc, tak jeden je hlavní, další jsou vedlejší. Vedlejší autor ale u nás může být i pokud je autor jen jeden, ale stránky nejsou přímo o té korporaci nebo osobě, např. zámek 002773528 (stránky jsou o zámku, asi je spravuje správa zámku, ale spadají pod NPÚ, proto je NPÚ jako vedlejší autor)

**Comment by Bystroushaak** [comment]
Díky!

**Comment by Bystroushaak** [comment]
Tak mě napadá ještě jeden dotaz - bylo by možné kopírovat ten řádek záznamu z autoritního do toho toho výstupu?

Myslím třeba to:

``1102    	|a Městské muzeum (Prachatice, Česko) |7 kn20050915083 |4 pbl``

rovnou takhle přenést do výstupu? Nebo se tam přenáší něco míň / víc?

**Comment by Bystroushaak** [comment]
Ok, tak jsem na tom zapracoval podle připomínek. Nyní se nedá vybrat autor jiný, než z autorit. Vydavatele je stále možné zadat ručně:

![1](https://cloud.githubusercontent.com/assets/227282/13551607/b6c57810-e33f-11e5-8f80-557f6cc09635.png)
![2](https://cloud.githubusercontent.com/assets/227282/13551611/cc30cec0-e33f-11e5-93ff-3acb3862b3ec.png)
![3](https://cloud.githubusercontent.com/assets/227282/13551613/cebe5bb2-e33f-11e5-8301-2d37a676ed14.png)
![4](https://cloud.githubusercontent.com/assets/227282/13551614/d077bd40-e33f-11e5-9dee-b77712e6feca.png)
![5](https://cloud.githubusercontent.com/assets/227282/13551615/d3488a86-e33f-11e5-9197-637e909e699f.png)

**Comment by bjackova** [comment]
Super, takhle je to úplně ideální a funguje :-)
