### ISSUE TITLE
Anglická verze konspektu

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#59]
Dostali jsme upozornění z autorit, že máme špatně vyplněné anglické kategorie konspektu u zdrojů vyplňovaných z WA Katu. Anglický konspekt má totiž jiné číslování, čísla českého a angl. konspektu se tedy neshodují.

**Comment by Bystroushaak** [comment]
Tohle je problém, který nejspíš nejsem schopný sám vyřešit.

@kvasnicaj nemáš někde něco, co by sedělo? Nebo nějakou překladovou tabulku?

**Comment by Bystroushaak** [comment]
Autoritní záznamy, pole 190 a 790.

**Comment by Bystroushaak** [comment]
Tohle se trochu komplikuje. Ptal jsem se na to Dana Kindla, který mi udělal půlhodinovou přednášku na téma, že české a anglické konspekty rozhodně nesedí 1:1 a ani jich není stejný počet (anglických je méně). K tomu jsme spolu navíc zjistili, že to co mi dal Jarda Kvalsnica je v podstatě naprosto nesmyslný set dat.

Validní mapování Český konspekt -> Anglický konspekt není nikde popsáno a nedá se jednoduše sehnat.

Pokusím se provést vlastní analýzu autoritní báze a vytvořit si vlastní, ale může to trvat a je to docela nejistá záležitost.

**Comment by Bystroushaak** [comment]
Od Dana jsem dneska dostal dataset, odkud to snad půjde vytáhnout v nějaké použitelné podobě.

**Comment by kvasnicaj** [comment]
Hele já na to teď koukal do naší databáze. A tam to prostě nějakým způsobem funguje. Když porovnáš anglický http://webarchiv.cz/en/browse/ a český katalog http://webarchiv.cz/cs/katalog-stranek/ 

tak ty kategorie prostě sedí, to znamená, že to prostě musí být nějak zpárované. Já se obávám, aby si datasetem od Dana nepřišel k jinému výsledku a nám se nerozbila naše databáze.

**Comment by Bystroushaak** [comment]
Což o to, ono to skoro u všech funguje. Pak jsou ale takové, kde to prostě nesedí. Pokud si na to stěžují z autorit, tak nevím, jak jinak to řešit, než že to založím na datech přímo z autorit.

**Comment by kvasnicaj** [comment]
Pak by se mělo tvoje mapování propsat do seederu a budeme používat to tvé i na frontendu. Co myslíš?

**Comment by Bystroushaak** [comment]
Nemám s tím problém, jen ho prvně budu muset vydolovat. Třeba se nakonec ukáže, že je to jen nějaká chybka kdesi, kde jí nikdo nečekal.

**Comment by Bystroushaak** [comment]
Kdyby měl někdo zájem, tak soubor s RAW datama konspektů je tady:
- [balkons1.xml.zip](https://github.com/WebArchivCZ/WA-KAT/files/163135/balkons1.xml.zip)

**Comment by Bystroushaak** [comment]
Hm. Tak z tohohle datasetu to nedostanu.

@kvasnicaj Jak jsi mi exportoval ty anglické v yamlu, mohl by jsi mi takhle vyexportovat i ty české? Chyba může být v tom, co jsem dostal od @Visgean

**Comment by Bystroushaak** [comment]
(https://github.com/WebArchivCZ/WA-KAT/blob/master/external_info/konspekt_en.yml)

**Comment by Bystroushaak** [comment]
Tak jsem se o tom ještě bavil s Danem. Ten mi vysvětlil, že ty anglické konspekty se v NKC nepoužívají, protože je to DDC, místo MDT, kde ty překlady prostě 1:1 nesedí. Proto se nedá párovat ten dataset česky : anglicky, alespoň ne podle těch identifikátorů, které tam jsou. Pokud tam máš někde překladovou tabulku, tak bych jí potřeboval dodat (teď mám český dataset, anglický dataset, ale žádný způsob, jak říct co k čemu patří, protože ty kódy jsou v jednom MDT a v druhém DDC).

**Comment by Bystroushaak** [comment]
Ha. Tak danovi se to ještě včera večer podařilo vytáhnout někde:

- [konspeng.xml.zip](https://github.com/WebArchivCZ/WA-KAT/files/164832/konspeng.xml.zip)

V brzké době to tam zapracuju.

**Comment by kvasnicaj** [comment]
hele tady je naše mapování, určitě to bude tím, že jsi neměl naše původní české :)

[wadminkonspekty.yml.gz](https://github.com/WebArchivCZ/WA-KAT/files/164885/wadminkonspekty.yml.gz)

**Comment by Bystroushaak** [comment]
Ahoj. Tenhle dataset je právě blbě. Když se podívašá třeba na ``Etnologie. Etnografie. Folklor``:

```YAML
  id: 1550
  conspectus_id: 1
  subcategory_id: 39
  subcategory: Etnologie. Etnografie. Folklor
  url: etnologie-etnografie-folklor
```

k tomu anglicky:

```YAML
  id: 1550
  conspectus_id: 1
  subcategory_id: 39
  subcategory: Customs, etiquette, folklore
  url: customs-etiquette-folklore
```

Všimni si, že mají stejné ``subcategory_id``, což je [MDT](https://cs.wikipedia.org/wiki/Mezin%C3%A1rodn%C3%AD_desetinn%C3%A9_t%C5%99%C3%ADd%C4%9Bn%C3%AD) (Mezinárodní Desetinné Třídění). Když se podívám do datasetu od Dana, tak tam má třeba následující záznam:

```XML
<record xmlns="http://www.loc.gov/MARC21/slim"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.loc.gov/MARC21/slim
http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
  <leader>     nz  a22     n  4500</leader>
  <datafield tag="190" ind1=" " ind2="7">
    <subfield code="a">39</subfield>
    <subfield code="x">Etnologie. Etnografie. Folklor</subfield>
    <subfield code="2">Konspekt</subfield>
    <subfield code="9">1</subfield>
  </datafield>
  <datafield tag="790" ind1="0" ind2="7">
    <subfield code="a">390</subfield>
    <subfield code="x">Customs, etiquette, folklore</subfield>
    <subfield code="2">Conspectus</subfield>
    <subfield code="9">1</subfield>
  </datafield>
</record>
```

Kde si všimni, že v `190 a` je to MDT *39*, a u anglického záznamu je to v ``790 a`` číslo *390*. To je to co jsem včera psal, že američani nepoužívají MDT, ale [DDT](https://en.wikipedia.org/wiki/Dewey_Decimal_Classification) (Dewey Decimal Classification), tudíž mají ty čísla jinak.

Teď je otázka, jak chceš abych to dělal. Osobně jsem v tomhle úplně neutrální a udělám to prostě jak si přeješ. Myslím ale, že tohle je právě ten důvod, proč Bára zakládala tuhle issue, protože autority to chtějí v DDC kódech, které v těch datasetech co jsem dostal nejsou.

**Comment by kvasnicaj** [comment]
Určitě použij ty datasety od Dana, to je bez debat. Mně unikl ten problém s MDT vs DDT. Já řešil jen konspekt vs conspectus. Důležitý je, aby to sedělo všude a fungovalo to pak i na úrovni té katalogizace.

**Comment by Bystroushaak** [comment]
Ok :)

**Comment by Bystroushaak** [comment]
Tak. Mělo by být opraveno. Prosím @bjackova o otestování.
