### ISSUE TITLE
Tvar data vzniku

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#65]
Bylo by možné přednastavit tvar data vzniku na takový: [XXXX?]- 
Je to obvyklý zápis, pokud je datum převzaté z jiného zdroje a není jisté, což je případ většiny webových zdrojů. Tvar by byl přednastavený s tím, že by bylo možné ho úplně přepsat (někdy je tvar jiný, ale je to méně případů).

**Comment by Bystroushaak** [comment]
Myslíš natvrdo, aby to bylo předvyplěneno v tom inputu? To není problém.

**Comment by bjackova** [comment]
V pořádku, funguje :)
