### ISSUE TITLE
Pole k převzetí z ISSN

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#66]
Z báze ISSN bychom pro časopisy rádi přejímali pole 222 (klíčový název), potom obsah pole PER do pole Periodicita a v případě, že tam bude pole 776, tak i to.

Pro časopisy se navíc vyplňují i další kódy v poli 008, jak už teď funguje propisování data vzniku sem, tak u časopisů by možná šlo takto propisovat z údajů v ISSN bázi pozici 18 (periodicita) a 19 (pravidelnost).

**Comment by Bystroushaak** [comment]
Ok, dávám do todo ještě na tuhle verzi.

**Comment by Bystroushaak** [comment]
Neměla bys nějaké ISSN z NTK alephu, na kterých by se to dalo otestovat?

**Comment by bjackova** [comment]
Například ISSN 2336-2022, 2336-2391, 2336-3657 nebo 1805-1111.

**Comment by Bystroushaak** [comment]
Můžu propisovat i tu periodicitu a tak, ale potřeboval bych pro jistotu ty konkrétní znaky vypsat, jestli počítáme oba od nuly, nebo to děláš od jedničky. V tomhle případě:

``131210c20079999xr-f||p|s||||||---b0mul-c``

Co je pro tebe na pozici 18 (periodicita) a 19 (pravidelnost) za znaky?

**Comment by bjackova** [comment]
Hm, tak jsem si všimla, že ISSN tu pravidelnost (19) zřejmě nepoužívá. Ale periodicitu (18) tam mají, v tomto případě je to kód f.

**Comment by Bystroushaak** [comment]
Ok, díky za info.
