### ISSUE TITLE
katalogizace 	https://casopisilegalit.wordpress.com

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/WA-KAT#70]
při ukládání záznamu zdroje https://casopisilegalit.wordpress.com se mi objevila následující -
[wa kat](https://cloud.githubusercontent.com/assets/13220888/13772893/cf1c407a-ea96-11e5-868b-a2ca56a957ff.png)
uložit to nešlo

**Comment by Bystroushaak** [comment]
Hm. To je zákeřné. Mrknu na to.

**Comment by Bystroushaak** [comment]
Omlouvám se. Chybu jsem udělal včera, když jsem přidával přenosy informací z alephu. Zapomněl jsem přidat větev kontrolující, zda informace byly poslané a když ne, tak se je nesnažit použít.
