### ISSUE TITLE
Chyba při načítání webů NPÚ

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#72]
![wakat-chyba](https://cloud.githubusercontent.com/assets/12845130/13873671/407c2718-ecf3-11e5-9825-0505db3ac34f.png)

Při vložení URL adresy některé ze stránek hradů Národního památkového ústavu to teď zahlásí tuhle chybu, u jiných zdrojů se mi to nestalo. Chybu to hlásí až cca od včera, předtím jsem zkatalogizovala spoustu hradů bez problému. 
Problém např. u URL http://www.hrad-landstejn.eu, http://www.hrad-rabi.eu nebo http://www.zamek-trebon.eu ...

**Comment by Bystroushaak** [comment]
Včera jsem nic ohledně tohohle neměnil. Koukám na ty weby a probíhá tam nějaká strašná prasárna v přesměrování.

**Comment by Bystroushaak** [comment]
Tak jsem vypnul ověřování validity certifikátu a nyní by to mělo fungovat.
