### ISSUE TITLE
seeder - vydavatelé

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/WA-KAT#76]
Při vyhledání nakladatele se zobrazí seznam zdrojů, které mu přísluší. Nemohl by být seznam uspořádaný abecedně bylo by to přehlednější. Např. u vydavatele Národní knihovna - tomu tak není.

**Comment by Bystroushaak** [comment]
Ahoj.

Nemá být tohle založeno jako issue v Seederu?

**Comment by Bilinova** [comment]
omlouvám se, skutečně to patří pod seeder.
