### ISSUE TITLE
Seeder-hlasování

### ISSUE THREAD

**Issue by Bilinova** [WebArchivCZ/WA-KAT#77]
Nelze uzavřít hlasování u nově vloženého zdroje (např. Staré Město). Jsem jeho správcem

**Comment by Bystroushaak** [comment]
Ahoj.

To asi nesouvisí s WA-KATem, ne? Nebo jaké hlasování myslíš?

**Comment by Bilinova** [comment]
omlouvám se, skutečně to patří pod seeder.
