### ISSUE TITLE
wa_kat_server.py pod jiným portem

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/WA-KAT#81]
Pouštím wa_kat_server.py supervisorem. Je možné nějak jednoduše aplikaci říci, aby se pustila na jiném portu? Defaultně ať jede klidně na 8080.

**Comment by Bystroushaak** [comment]
V konfiguráku se dá nastavit jiný port. Viz http://wa-kat.readthedocs.io/en/latest/admin_manual.html#nastaveni-webu

V podstatě tedy vytvořit ``/etc/webarchive/wa_kat.json`` s něčím jako:

```JSON
{
    "WEB_PORT": 2222,
}
```

**Comment by westfood** [comment]
Jsem si nevšiml, že k tomu máš manuál!

Dne čtvrtek 2. června 2016 Bystroushaak <notifications@github.com>
napsal(a):
