### ISSUE TITLE
wa-kat za nginx?

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/WA-KAT#83]
Ahoj, nemáš nějak dokumentaci jak ideálně rozběhnout ten zeo server za nginx? Případně jste měli jiný nápad jak bude seeder a wa-kat fungovat?

moje představa je vše na portu 80, dělení jen podle složek

/ seeder produkce
/wa-kat produkce
/dev/seeder testavací docker
/dev/wa-kat testovací docker

**Comment by Bystroushaak** [comment]
ZEO server je databáze. To by nemělo hrát žádnou roli.

nginx jsem takhle nikdy nekonfiguroval. Mělo by stačit jen nějak mapovat porty na složky, ne? Tzn jedeš WA-KAT na 9000 třeba a řekneš nginxu, aby ti to mapoval na /wa-kat

**Comment by westfood** [comment]
Kej, otestuju.

Dne pondělí 6. června 2016 Bystroushaak <notifications@github.com>
napsal(a):

**Comment by westfood** [comment]
OK, cajk:

kat.webarchiv.cz

location / {
    proxy_pass http://127.0.0.1:10001;
proxy_redirect     off;

proxy_set_header   Host              $host;
proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto $scheme;
