### ISSUE TITLE
Nefunkční WA KAT

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#84]
WA KAT aktuálně (od pátku) nefunguje (chyba: Unable to connect - Firefox can't establish a connection to the server at forpsi.kitakitsune.org:8080.)

**Comment by Bystroushaak** [comment]
Ahoj.

To demo jsem vypnul, Ruda psal v https://github.com/WebArchivCZ/WA-KAT/issues/82 že už mu to jede na oficiálním serveru.

**Comment by Bystroushaak** [comment]
@westfood Nebo mám to demo nechat pořád běžet?

**Comment by westfood** [comment]
čéšť, jsem to chtěl nahodit se seederem dneska po poradě, ale jsem nemocnej. Tak to demo prosím nech ještě týden běžet, ve středu budu v hostíku a nahodím to.

**Comment by westfood** [comment]
tuhle středu..

**Comment by Bystroushaak** [comment]
Kk

**Comment by Bystroushaak** [comment]
Ono nejde ani tak o to, že bych to nechtěl nechat běžet, ale spadl mi server a nechtělo se mi s tím hrabat.

**Comment by Bystroushaak** [comment]
Už to běží.
