### ISSUE TITLE
Datum vzniku

### ISSUE THREAD

**Issue by bjackova** [WebArchivCZ/WA-KAT#85]
Aplikace teď rovnou doplní všude rok 2009 bez rozbalovací nabídky různých variant jako dřív.

**Comment by Bystroushaak** [comment]
Mrknu na to. Je to dost divné, nejspíš chyba někde v komponentách třetích stran.

**Comment by Bystroushaak** [comment]
Jop. Whois detektor spoléhal na nějaký web, který teď vrací blbosti. Zjistím jak to opravit.

**Comment by Bystroushaak** [comment]
Tak ne whois, ale memento web zavřel staré API.

**Comment by Bystroushaak** [comment]
Tak, už to funguje. Teď se to dá normálně rozkliknout a nabídne ti to alternativy, jako dřív.

@westfood Pokud máš nasazeno někde interně, tak doporučuji updatovat. Vydal jsem novou pip verzi.
