### ISSUE TITLE
generování MDT – pole 080

### ISSUE THREAD

**Issue by mariehaskovcova** [WebarchivCZ/WA-KAT#90]

**Comment by mariehaskovcova** [comment]
při generování kódů mezinárodního desetinného třídění, pole 080 se občas generují v Alephu blbosti, např. 4 pole jsou ok, jedno vypadá takto:
002876403 080   L $$a94(100)&amp;quot;1939/1945&amp;quot;$$2MRF

**Comment by Bystroushaak** [comment]
Ahoj.

Můžeš prosím poslat screenshot vstupních dat z wa-katu?

**Comment by mariehaskovcova** [comment]
Ahoj, stačí takto? Je to na dvě části

http://prnt.sc/e62tpp
http://prnt.sc/e62ubx

**Comment by Bystroushaak** [comment]
Jo, díky. ISSN jsi nevyplňovala?

**Comment by mariehaskovcova** [comment]
nevyplňovala, je to zdroj, který ISSN nemá

**Comment by Bystroushaak** [comment]
Super, mrknu na to a pokusím se to opravit co nejdřív. Nemám teď ale moc času, tak se k tomu možná dostanu až o víkendu. Každopádně na tom budu pracovat. Díky za ohlášení.

**Comment by mariehaskovcova** [comment]
díky :)

**Comment by Bystroushaak** [comment]
Jen pro archivní účely ještě přikládám screeny přímo na github, kdyby náhodou to print.sc ty screeny smazalo:

![5ebf22dfce2a4389985cc9a315953fb8](https://cloud.githubusercontent.com/assets/227282/22747419/5485fadc-ee27-11e6-8de1-492da1a8dd6c.png)
![fd3bd3af512c4d68bed5fa08ca8a44b4](https://cloud.githubusercontent.com/assets/227282/22747424/560219fe-ee27-11e6-9ef0-1f45c1347d83.png)

**Comment by Bystroushaak** [comment]
Jedná se o nepřevedené HTML entity. Kód generátoru keywordů jsem opravil. Z alephu teď tahám dalších 40 000 záznamů, až se stáhnou, tak to přegeneruji a mělo by to být ok.

**Comment by Bystroushaak** [comment]
Opraveno. Vydal jsem novou verzi 1.1.5.

Prosím @westfood o nasazení nové verze (opět Docker s parametrem ``--no-cache``).
