### ISSUE TITLE
Co to integrovat se Sentry

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/WA-KAT#92]
Ahoj, pro Seeder používáme Sentry. Možná by stálo za to, aby nám sentry kontroloval agregoval chybovky.. co říkáš? // http://sentry.webarchiv.cz

**Comment by Bystroushaak** [comment]
Ok. Přidával jsem tam modul pro logování, který to teď loguje ke mě na server. Neměl by být problém to upravit, aby to logovalo sem. Můžeš mi k tomu poslat nějaké přihlašovací údaje, nebo tak něco?

**Comment by Bystroushaak** [comment]
Jinak já se asi budu do středy ještě flákat, ve čtvrtek se pak nejspíš pustím do implementace zbytku todo. Ohledně toho bych asi potřeboval zajet a ještě to probrat.

**Comment by westfood** [comment]
Jára tu bude až od 20tého.

Poslal jsem ti pozvánku do sentry.

**Comment by Bystroushaak** [comment]
Uhm. Na kterej email? Co tak koukám, tak nikde nic nevidím, ani ve spamu.

**Comment by westfood** [comment]
bystrousak@kitakitsune.org

**Comment by Bystroushaak** [comment]
Ok, tak možná je jen zaseklé zoho, snad to přijde.

**Comment by Bystroushaak** [comment]
Crosslink WebArchivCZ/Seeder#14

**Comment by westfood** [comment]
Tak trable možná na mé straně, host nezná smtp.nkp.cz, dávám to na IP.. chvilku potrvá než se to zpropaguje

**Comment by westfood** [comment]
tak teď snad už cajk

**Comment by Bystroushaak** [comment]
Už to došlo, díky. Mrknu na to zítra.

**Comment by kvasnicaj** [comment]
@Bystroushaak napiš mi prosím na email, kdy by se ti to hodilo ten týden po 20. 3. a můžeme se sejít :)

**Comment by Bystroushaak** [comment]
Ok, implementováno, teď to tam bleje všechny možné logovací zprávy. Aby to chodilo, přidal jsem dvě proměnné do ``settings.py`` (nastavují se přes ``settings.json``):

```JSON
{
    "LOG_TO_SENTRY": true,
    "SENTRY_DSN": "http://24f...80@sentry.webarchiv.cz/5"
}
```

Pozor na to ``SENTRY_DSN``, protože to vaše web gui tam bleje blbou adresu ve formátu:

```
http://24f...80@10.3.0.20:9000/5
```

Což je nejspíš blbě jak ta IP adresa, tak ten port. S tím ``sentry.webarchiv.cz/5`` jsem to otestoval a fungovalo to.

**Comment by Bystroushaak** [comment]
Jo, málem bych zapomněl - vydal jsem novou verzi, kde je sentry integrováno.

**Comment by westfood** [comment]
Nahodil jsem novou verzi přes Docker, ta integreace se Seederem bude fachat?

**Comment by westfood** [comment]
Seeder=Sentry

**Comment by Bystroushaak** [comment]
Mno. Funguje, ale musíš tam vyplnit to DSN do konfiguráku, který máš v dockeru. Můžu ti ho poslat emailem.

**Comment by Bystroushaak** [comment]
To je podobné jako třeba s tim seeder API tokenem.

**Comment by Bystroushaak** [comment]
Poslal jsem na mail.

**Comment by westfood** [comment]
Jasně, máš to v dokumentaci?

**Comment by Bystroushaak** [comment]
Mno, v dokumentaci to je, teď je otázka, jestli se to propsalo na readthedocs. Mrknu, případně fixnu.

**Comment by Bystroushaak** [comment]
Jop, chtělo to prošťouchnout: http://wa-kat.readthedocs.io/en/latest/admin_manual.html#nastaveni-logovani

**Comment by westfood** [comment]
díkes!

2017-03-16 19:05 GMT+01:00 Bystroushaak <notifications@github.com>:
